plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework:spring-web'
    api 'com.fasterxml.jackson.core:jackson-annotations'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}