name: 기능 추가
description: 새로운 기능을 제안합니다.
title: "[Feature] "
labels:
  - feature

body:
  - type: textarea
    id: work
    attributes:
      label: 작업 내용
      placeholder: |
        - [ ] API 추가
        - [ ] Service 구현
        - [ ] 테스트 작성
    validations:
      required: true