plugins {
    id 'java-library'
}

description = 'core-kafka'

dependencies {
    api 'org.springframework.kafka:spring-kafka'
    api 'org.springframework.boot:spring-boot-starter-json'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}