syntax = "proto3";

package tikitaka.member.v1;

option java_package = "tikitaka.core.grpc.member";
option java_outer_classname = "MemberProto";
option java_multiple_files = true;

service MemberService {

  rpc GetMember(GetMemberRequest) returns (GetMemberResponse);
}

service CorporationService {

  rpc GetCorporation(GetCorporationRequest) returns (GetCorporationResponse);
}

message GetMemberRequest {

  string id = 1;
}

message GetMemberResponse {

  Member member = 1;
}

message GetCorporationRequest {

  string id = 1;
}

message GetCorporationResponse {

  Corporation corporation = 1;
}

message Member {

  string id = 1;

  string username = 2;

  string email = 3;

  string phone = 4;

}

message Corporation {

  string id = 1;

  string username = 2;

  string email = 3;

  string phone = 4;
}